### ISSUE TITLE
Add a really simple abstract component to be used as base class for component wrappers

### ISSUE THREAD

**Issue by mstahv** [vaadin/serverside-elements#5]
Currently there is no good base class if you want to wrap an element as a real Vaadin component. AbstractJavaScriptComponent good, but that "dies" without a JS file with a dummy implementation. CssLayout is one option, but that pollutes the server side API with component container APIs.

It might be a good idea to add such to this library.

cc: @alejandro-du

**Comment by Legioth** [comment]
This component could optimally support having any element type, instead of the hardcoded `<div>` that you'd get from AbstractJavaScriptComponent or CssLayout.

**Comment by mstahv** [comment]
That would be a plus, but even just a static div based empty "root component" would help a lot.
